### PR TITLE
Sonar scan opt in

### PR DESCRIPTION
**Pull request by sdulgunti**

### CODE REVIEW

**Comment by kd7lxl** [comment]
Please submit PRs from forks rather than pushing to this repo directly.

**Review by kd7lxl — COMMENTED** [review]
Should we be able to see a Sonar comment in this PR to see that it's working?

**Comment by sdulgunti** [comment]
> Should we be able to see a Sonar comment in this PR to see that it's working?

Yes Tom, I am checking why PR decoration hasn't worked for this pr.

**Comment by sdulgunti** [comment]
> Please submit PRs from forks rather than pushing to this repo directly.
Closing this PR and working on new PR from fork: https://github.com/infobloxopen/tugger/pull/46

**Pull request closed without merging**
